# Day mapping for openHour
day_mapping = {
    1: "monday",
    2: "tuesday",
    3: "wednesday",
    4: "thursday",
    5: "friday",
    6: "saturday",
    7: "sunday"
}

server_categories_map = {
    "service": "Dịch vụ",
    "placeholder": "Chọn dịch vụ",
    "service_desc": "Thêm thông tin dịch vụ cho cửa hàng",
    "air_conditioning": "Điều hòa",
    "open_24_7": "Mở cửa 24/7",
    "suitable_for_groups": "Phù hợp nhóm bạn",
    "child_area": "Khu trẻ em",
    "private_room": "Phòng riêng",
    "child_friendly": "Phù hợp cho trẻ",
    "pet_friendly": "Cho phép thú cưng",
    "parking": "Bãi đậu ô tô",
    "restroom": "Nhà vệ sinh",
    "outdoor_seating": "Bàn ngoài trời",
    "free_parking": "Gửi xe miễn phí",
    "accepts_cards": "Trả thẻ",
    "romantic_style": "Kiểu lãng mạn",
    "special_occasion": "Dịp đặc biệt",
    "family_friendly": "Phù hợp gia đình",
    "wifi_available": "Có wifi",
    "delivery": "Giao hàng",
    "music_available": "Có nhạc",
    "on_site_sales": "Bán tại chỗ",
    "takeout": "Bán mang đi",
    "reservations": "Cho phép đặt bàn trước",
    "smoking_area": "Khu hút thuốc",
    "placeholder": "Chọn danh mục",
    "dish": "Loại đồ ăn",
    "Yogurt": "Da ua",
    "dish_desc": "Món ăn của bạn thuộc loại nào?",
    "grilled_food": "Đồ nướng",
    "snacks": "Đồ ăn vặt",
    "korean_dishes": "Món Hàn",
    "hotpot": "Lẩu",
    "snails_seafood": "Ốc - hải sản",
    "healthy_food": "Healthy",
    "chinese_dishes": "Món Hoa",
    "european_dishes": "Món Âu",
    "categories": "Danh mục",
    "categories_desc": "Hãy chọn danh mục phù hợp.",
    "cocktail": "Cocktail",
    "beer": "Bia",
    "liquor": "Rượu",
    "other_categories": "Danh mục khác",
    "alcoholic_beverages": "Thức uống có cồn",
    "fruit_tea": "Trà trái cây",
    "pudding_milk_tea": "Trà sữa pudding",
    "oolong_milk_tea": "Trà sữa ô long",
    "milk_tea_with_rose": "Hồng trà sữa",
    "fruit_flavored_milk_tea": "Trà sữa vị trái cây",
    "cheese_cream_milk_tea": "Trà sữa kem cheese",
    "japanese_dishes": "Món Nhật",
    "sushi": "Sushi",
    "milk_coffee": "Cà phê sữa",
    "black_coffee": "Cà phê đen",
    "cappuccino": "Cappuccino",
    "tea": "Trà",
    "coffee": "Cà phê",
    "salad": "Gỏi",
    "steamed_fish": "Cá hấp",
    "grilled_hot_pot": "Lẩu nướng",
    "beef_steak": "Beef steak",
    "pastries": "Bánh ngọt",
    "peach_tea": "Trà đào",
    "lychee_tea": "Trà vải",
    "seafood_hot_pot": "Lẩu hải sản",
    "fresh_seafood": "Hải sản tươi sống",
    "grilled_meat": "Thịt nướng",
    "rum": "Rum",
    "milk_tea": "Trà sữa",
    "beef_noodle_soup": "Bún bò",
    "fish_noodle_soup": "Bún cá",
    "juice": "Nước ép",
    "chicken_rice": "Cơm gà",
    "pho": "Phở",
    "beef_pho": "Phở bò",
    "rice_meal": "Cơm phần",
    "savory_cakes": "Bánh mặn",
    "iced_tea": "Trà đá",
    "vietnamese_steamed_rice_rolls": "Cuốn",
    "steamed": "Kiểu hấp",
    "vietnamese_iced_coffee_with_milk": "Bạc xĩu",
    "crab_soup": "Súp cua",
    "gotu_kola": "Nước rau má",
    "clay_pot_rice": "Cơm niêu",
    "beef_rice": "Cơm bò",
    "office_lunch": "Cơm văn phòng",
    "herbal_tea": "Trà thảo mộc",
    "seafood_buffet": "Buffet hải sản",
    "glass_noodles": "Miến",
    "spaghetti": "Mì Ý",
    "grilling": "Kiểu nướng",
    "vietnamese_drip_coffee": "Cà phê vợt",
    "blended_iced_coffee": "Cà phê đá xay",
    "vietnamese_rice_paper_salad": "Bánh tráng trộn",
    "fried_noodles": "Mì xào",
    "fish_salad": "Gỏi cá",
    "fried_fish_balls": "Cá viên chiên",
    "chicken_hot_pot": "Lẩu gà",
    "grilled_beef": "Bò nướng",
    "grilled_chicken": "Gà nướng",
    "frog_hot_pot": "Lẩu ếch",
    "boiled_chicken": "Gà luộc",
    "chicken_cartilage": "Sụn gà",
    "steamed_shrimp": "Tôm hấp",
    "french_fries": "Khoai tây chiên",
    "tofu": "Tàu hủ",
    "western_dishes": "Món Âu",
    "orange_juice": "Nước cam",
    "mediterranean_grilled_seafood": "Hải sản nướng kiểu Địa Trung Hải",
    "skewers": "Xiên nướng",
    "latte": "Latte",
    "mixed_sweet_soup": "Chè thập cẩm",
    "longan_sweet_soup": "Chè nhãn nhục",
    "detox_tea": "Trà thanh nhiệt",
    "vietnamese_noodle_with_shrimp_paste": "Bún đậu mắm tôm",
    "vietnamese_crab_noodle_soup": "Bún riêu",
    "hanoi_grilled_pork_noodle": "Bún chả Hà Nội",
    "snails": "Ốc",
    "seafood": "Hải sản",
    "rice_noodle": "Hủ tiếu",
    "dry_rice_noodle": "Hủ tiếu khô",
    "rice": "Cơm",
    "soup": "Canh",
    "porridge": "Cháo",
    "turkish_bread": "Bánh mì Thổ Nhĩ Kỳ",
    "plain_porridge": "Cháo trắng",
    "blended_iced_drinks": "Đồ uống đá xay",
    "soft_drinks": "Nước ngọt",
    "vegetable_salad": "Salad rau củ",
    "broken_rice": "Cơm tấm",
    "grilled_pork_noodle": "Bún thịt nướng",
    "pork_chop_rice": "Cơm sườn",
    "pork_rib_porridge": "Cháo sườn",
    "toasted_bread": "Bánh mì nướng",
    "fruit_smoothies": "Sinh tố hoa quả",
    "fast_food": "Thức ăn nhanh",
    "fried_chicken": "Gà rán",
    "vietnamese_iced_coffee": "Bạc xỉu",
    "hot_pot": "Lẩu",
    "japanese_street_food": "Street food Nhật",
    "egg_coffee": "Cà phê trứng",
    "rice_pancakes": "Bánh cuốn",
    "fried_spring_rolls": "Nem rán (chả giò)",
    "bread": "Bánh mì",
    "grilled_pork_skewers": "Nem nướng",
    "crab_hot_pot": "Lẩu cua đồng",
    "yangzhou_fried_rice": "Cơm chiên Dương Châu",
    "thai_salad": "Gỏi Thái",
    "fruit": "Trái cây",
    "noodle_soup": "Bún",
    "beef_stew": "Bò sốt vang",
    "porridge_with_offal": "Cháo lòng",
    "fried_sausage": "Dồi rán",
    "boiled_offal": "Lòng luộc",
    "sausage": "Dồi",
    "vietnamese_dishes": "Món Việt Nam",
    "taiwanese_milk_tea": "Trà sữa Đài Loan"
  }

type_map = {
    "play": [
        "beer",
        "japanese_street_food",
        "cocktail",
        "soft_drinks",
        "alcoholic_drinks",
        "fruit_tea",
        "egg_coffee",
        "peach_tea",
        "lychee_tea",
        "blended_drinks",
        "smoothie",
        "milk_tea",
        "fruit_juice",
        "desserts",
        "snack"
    ],
    "date_night": [
        "coffee",
        "bac_xiu",
        "blended_drinks",
        "black_coffee",
        "milk_coffee",
        "cappuccino",
        "milk_tea",
        "pudding_milk_tea",
        "oolong_milk_tea",
        "milk_tea_with_black_tea",
        "fruit_flavored_milk_tea",
        "cheese_cream_milk_tea",
        "wine",
        "fruit_cocktail",
        "green_tea"
    ],
    "family_meal": [
        "hotpot",
        "steamed_shrimp",
        "fish_salad",
        "chicken_hotpot",
        "crab_hotpot",
        "vermicelli",
        "hanoi_grilled_pork_noodles",
        "rice_rolls",
        "fried_spring_rolls",
        "bread",
        "grilled_spring_rolls",
        "snails",
        "yangzhou_fried_rice",
        "thai_salad",
        "beef_stew",
        "beef_steak",
        "offal_porridge",
        "fried_sausage",
        "boiled_offal",
        "steamed_fish",
        "grilled_hotpot",
        "vietnamese_dishes",
        "broken_rice",
        "grilled_ribs",
        "quang_noodles",
        "la_vong_fish_cake",
        "sour_soup",
        "fried_chicken"
    ],
    "outdoor": [
        "seafood",
        "salad",
        "fruits",
        "orange_juice",
        "bread_sticks",
        "sticky_rice",
        "grilled_meat",
        "bbq_grilled_food",
        "takeaway_milk_tea",
        "ice_cream",
        "snacks",
        "spring_rolls",
        "rice_paper_rolls"
    ],
    "dating": [
        "seafood",
        "salad",
        "fruits",
        "orange_juice",
        "bread_sticks",
        "sticky_rice",
        "grilled_meat",
        "bbq_grilled_food",
        "takeaway_milk_tea",
        "ice_cream",
        "snacks",
        "spring_rolls",
        "rice_paper_rolls"
    ],
    "travel": [
        "seafood",
        "salad",
        "fruits",
        "orange_juice",
        "bread_sticks",
        "sticky_rice",
        "grilled_meat",
        "bbq_grilled_food",
        "takeaway_milk_tea",
        "ice_cream",
        "snacks",
        "spring_rolls",
        "rice_paper_rolls"
    ],
    "sports": [],
    "cinema": ["popcorn", "soft_drinks", "snacks", "milk_tea", "fruit_tea"],
    "nature": ["fruits", "snacks", "smoothie", "ice_cream", "orange_juice"],
    "health_care": ["fruit_juice", "herbal_tea", "green_tea", "smoothie", "salad"],
    "music": ["music"],
    "theaters_art": ["theaters", "art"],
    "sport": ["sport"],
    "game": ["game"],
    "dance": ["dance"]
}